version: '3.8'
services:
  blogapp:
    build: ./
    ports:
      - 3001:3001
  db:
    image: mongo:4.0.28-xenial
    ports:
      - 27017:27017
    volumes:
      - blogapp:/data/db
volumes:
  blogapp:
